# Generated by Django 4.1.9 on 2023-06-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("from_who", models.CharField(max_length=10)),
                ("to", models.CharField(max_length=10)),
                ("text", models.CharField(max_length=160)),
            ],
        ),
    ]
